/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AugmentsRouteImport } from './routes/augments'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as LittleLegendsRouteImport } from './routes/little-legends'
import { Route as TraitsRouteImport } from './routes/traits'
import { Route as ChampionsApiNameRouteImport } from './routes/champions_.$apiName'
import { Route as CompsSlugRouteImport } from './routes/comps/$slug'
import { Route as ItemsApiNameRouteImport } from './routes/items_.$apiName'
import { Route as TierlistAugmentsRouteImport } from './routes/tierlist/augments'
import { Route as TierlistChampionsRouteImport } from './routes/tierlist/champions'
import { Route as TierlistChangesRouteImport } from './routes/tierlist/changes'
import { Route as TierlistCompsRouteImport } from './routes/tierlist/comps'
import { Route as TierlistItemsRouteImport } from './routes/tierlist/items'
import { Route as TierlistTraitsRouteImport } from './routes/tierlist/traits'
import { Route as ToolsComponentsRouteImport } from './routes/tools/components'
import { Route as ToolsRollingRouteImport } from './routes/tools/rolling'
import { Route as TraitsApiNameRouteImport } from './routes/traits_.$apiName'
import { Route as CompsAutoIdRouteImport } from './routes/comps/auto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AugmentsRoute = AugmentsRouteImport.update({
  id: '/augments',
  path: '/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const LittleLegendsRoute = LittleLegendsRouteImport.update({
  id: '/little-legends',
  path: '/little-legends',
  getParentRoute: () => rootRouteImport,
} as any)
const TraitsRoute = TraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsApiNameRoute = ChampionsApiNameRouteImport.update({
  id: '/champions_/$apiName',
  path: '/champions/$apiName',
  getParentRoute: () => rootRouteImport,
} as any)
const CompsSlugRoute = CompsSlugRouteImport.update({
  id: '/comps/$slug',
  path: '/comps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsApiNameRoute = ItemsApiNameRouteImport.update({
  id: '/items_/$apiName',
  path: '/items/$apiName',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistAugmentsRoute = TierlistAugmentsRouteImport.update({
  id: '/tierlist/augments',
  path: '/tierlist/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistChampionsRoute = TierlistChampionsRouteImport.update({
  id: '/tierlist/champions',
  path: '/tierlist/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistChangesRoute = TierlistChangesRouteImport.update({
  id: '/tierlist/changes',
  path: '/tierlist/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistCompsRoute = TierlistCompsRouteImport.update({
  id: '/tierlist/comps',
  path: '/tierlist/comps',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistItemsRoute = TierlistItemsRouteImport.update({
  id: '/tierlist/items',
  path: '/tierlist/items',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistTraitsRoute = TierlistTraitsRouteImport.update({
  id: '/tierlist/traits',
  path: '/tierlist/traits',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsComponentsRoute = ToolsComponentsRouteImport.update({
  id: '/tools/components',
  path: '/tools/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRollingRoute = ToolsRollingRouteImport.update({
  id: '/tools/rolling',
  path: '/tools/rolling',
  getParentRoute: () => rootRouteImport,
} as any)
const TraitsApiNameRoute = TraitsApiNameRouteImport.update({
  id: '/traits_/$apiName',
  path: '/traits/$apiName',
  getParentRoute: () => rootRouteImport,
} as any)
const CompsAutoIdRoute = CompsAutoIdRouteImport.update({
  id: '/comps/auto/$id',
  path: '/comps/auto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/items': typeof ItemsRoute
  '/little-legends': typeof LittleLegendsRoute
  '/traits': typeof TraitsRoute
  '/champions/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/items/$apiName': typeof ItemsApiNameRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/changes': typeof TierlistChangesRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
  '/tools/components': typeof ToolsComponentsRoute
  '/tools/rolling': typeof ToolsRollingRoute
  '/traits/$apiName': typeof TraitsApiNameRoute
  '/comps/auto/$id': typeof CompsAutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/items': typeof ItemsRoute
  '/little-legends': typeof LittleLegendsRoute
  '/traits': typeof TraitsRoute
  '/champions/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/items/$apiName': typeof ItemsApiNameRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/changes': typeof TierlistChangesRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
  '/tools/components': typeof ToolsComponentsRoute
  '/tools/rolling': typeof ToolsRollingRoute
  '/traits/$apiName': typeof TraitsApiNameRoute
  '/comps/auto/$id': typeof CompsAutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/items': typeof ItemsRoute
  '/little-legends': typeof LittleLegendsRoute
  '/traits': typeof TraitsRoute
  '/champions_/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/items_/$apiName': typeof ItemsApiNameRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/changes': typeof TierlistChangesRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
  '/tools/components': typeof ToolsComponentsRoute
  '/tools/rolling': typeof ToolsRollingRoute
  '/traits_/$apiName': typeof TraitsApiNameRoute
  '/comps/auto/$id': typeof CompsAutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/compare'
    | '/explorer'
    | '/items'
    | '/little-legends'
    | '/traits'
    | '/champions/$apiName'
    | '/comps/$slug'
    | '/items/$apiName'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/changes'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
    | '/tools/components'
    | '/tools/rolling'
    | '/traits/$apiName'
    | '/comps/auto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/compare'
    | '/explorer'
    | '/items'
    | '/little-legends'
    | '/traits'
    | '/champions/$apiName'
    | '/comps/$slug'
    | '/items/$apiName'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/changes'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
    | '/tools/components'
    | '/tools/rolling'
    | '/traits/$apiName'
    | '/comps/auto/$id'
  id:
    | '__root__'
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/compare'
    | '/explorer'
    | '/items'
    | '/little-legends'
    | '/traits'
    | '/champions_/$apiName'
    | '/comps/$slug'
    | '/items_/$apiName'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/changes'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
    | '/tools/components'
    | '/tools/rolling'
    | '/traits_/$apiName'
    | '/comps/auto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AugmentsRoute: typeof AugmentsRoute
  BuilderRoute: typeof BuilderRoute
  ChampionsRoute: typeof ChampionsRoute
  CompareRoute: typeof CompareRoute
  ExplorerRoute: typeof ExplorerRoute
  ItemsRoute: typeof ItemsRoute
  LittleLegendsRoute: typeof LittleLegendsRoute
  TraitsRoute: typeof TraitsRoute
  ChampionsApiNameRoute: typeof ChampionsApiNameRoute
  CompsSlugRoute: typeof CompsSlugRoute
  ItemsApiNameRoute: typeof ItemsApiNameRoute
  TierlistAugmentsRoute: typeof TierlistAugmentsRoute
  TierlistChampionsRoute: typeof TierlistChampionsRoute
  TierlistChangesRoute: typeof TierlistChangesRoute
  TierlistCompsRoute: typeof TierlistCompsRoute
  TierlistItemsRoute: typeof TierlistItemsRoute
  TierlistTraitsRoute: typeof TierlistTraitsRoute
  ToolsComponentsRoute: typeof ToolsComponentsRoute
  ToolsRollingRoute: typeof ToolsRollingRoute
  TraitsApiNameRoute: typeof TraitsApiNameRoute
  CompsAutoIdRoute: typeof CompsAutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/augments': {
      id: '/augments'
      path: '/augments'
      fullPath: '/augments'
      preLoaderRoute: typeof AugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/little-legends': {
      id: '/little-legends'
      path: '/little-legends'
      fullPath: '/little-legends'
      preLoaderRoute: typeof LittleLegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traits': {
      id: '/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof TraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions_/$apiName': {
      id: '/champions_/$apiName'
      path: '/champions/$apiName'
      fullPath: '/champions/$apiName'
      preLoaderRoute: typeof ChampionsApiNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comps/$slug': {
      id: '/comps/$slug'
      path: '/comps/$slug'
      fullPath: '/comps/$slug'
      preLoaderRoute: typeof CompsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$apiName': {
      id: '/items_/$apiName'
      path: '/items/$apiName'
      fullPath: '/items/$apiName'
      preLoaderRoute: typeof ItemsApiNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/augments': {
      id: '/tierlist/augments'
      path: '/tierlist/augments'
      fullPath: '/tierlist/augments'
      preLoaderRoute: typeof TierlistAugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/champions': {
      id: '/tierlist/champions'
      path: '/tierlist/champions'
      fullPath: '/tierlist/champions'
      preLoaderRoute: typeof TierlistChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/changes': {
      id: '/tierlist/changes'
      path: '/tierlist/changes'
      fullPath: '/tierlist/changes'
      preLoaderRoute: typeof TierlistChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/comps': {
      id: '/tierlist/comps'
      path: '/tierlist/comps'
      fullPath: '/tierlist/comps'
      preLoaderRoute: typeof TierlistCompsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/items': {
      id: '/tierlist/items'
      path: '/tierlist/items'
      fullPath: '/tierlist/items'
      preLoaderRoute: typeof TierlistItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/traits': {
      id: '/tierlist/traits'
      path: '/tierlist/traits'
      fullPath: '/tierlist/traits'
      preLoaderRoute: typeof TierlistTraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/components': {
      id: '/tools/components'
      path: '/tools/components'
      fullPath: '/tools/components'
      preLoaderRoute: typeof ToolsComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rolling': {
      id: '/tools/rolling'
      path: '/tools/rolling'
      fullPath: '/tools/rolling'
      preLoaderRoute: typeof ToolsRollingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traits_/$apiName': {
      id: '/traits_/$apiName'
      path: '/traits/$apiName'
      fullPath: '/traits/$apiName'
      preLoaderRoute: typeof TraitsApiNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comps/auto/$id': {
      id: '/comps/auto/$id'
      path: '/comps/auto/$id'
      fullPath: '/comps/auto/$id'
      preLoaderRoute: typeof CompsAutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AugmentsRoute: AugmentsRoute,
  BuilderRoute: BuilderRoute,
  ChampionsRoute: ChampionsRoute,
  CompareRoute: CompareRoute,
  ExplorerRoute: ExplorerRoute,
  ItemsRoute: ItemsRoute,
  LittleLegendsRoute: LittleLegendsRoute,
  TraitsRoute: TraitsRoute,
  ChampionsApiNameRoute: ChampionsApiNameRoute,
  CompsSlugRoute: CompsSlugRoute,
  ItemsApiNameRoute: ItemsApiNameRoute,
  TierlistAugmentsRoute: TierlistAugmentsRoute,
  TierlistChampionsRoute: TierlistChampionsRoute,
  TierlistChangesRoute: TierlistChangesRoute,
  TierlistCompsRoute: TierlistCompsRoute,
  TierlistItemsRoute: TierlistItemsRoute,
  TierlistTraitsRoute: TierlistTraitsRoute,
  ToolsComponentsRoute: ToolsComponentsRoute,
  ToolsRollingRoute: ToolsRollingRoute,
  TraitsApiNameRoute: TraitsApiNameRoute,
  CompsAutoIdRoute: CompsAutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
