/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AugmentsRouteImport } from './routes/augments'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as TraitsRouteImport } from './routes/traits'
import { Route as ChampionsApiNameRouteImport } from './routes/champions_.$apiName'
import { Route as CompsSlugRouteImport } from './routes/comps/$slug'
import { Route as TierlistAugmentsRouteImport } from './routes/tierlist/augments'
import { Route as TierlistChampionsRouteImport } from './routes/tierlist/champions'
import { Route as TierlistCompsRouteImport } from './routes/tierlist/comps'
import { Route as TierlistItemsRouteImport } from './routes/tierlist/items'
import { Route as TierlistTraitsRouteImport } from './routes/tierlist/traits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AugmentsRoute = AugmentsRouteImport.update({
  id: '/augments',
  path: '/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const TraitsRoute = TraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsApiNameRoute = ChampionsApiNameRouteImport.update({
  id: '/champions_/$apiName',
  path: '/champions/$apiName',
  getParentRoute: () => rootRouteImport,
} as any)
const CompsSlugRoute = CompsSlugRouteImport.update({
  id: '/comps/$slug',
  path: '/comps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistAugmentsRoute = TierlistAugmentsRouteImport.update({
  id: '/tierlist/augments',
  path: '/tierlist/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistChampionsRoute = TierlistChampionsRouteImport.update({
  id: '/tierlist/champions',
  path: '/tierlist/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistCompsRoute = TierlistCompsRouteImport.update({
  id: '/tierlist/comps',
  path: '/tierlist/comps',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistItemsRoute = TierlistItemsRouteImport.update({
  id: '/tierlist/items',
  path: '/tierlist/items',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistTraitsRoute = TierlistTraitsRouteImport.update({
  id: '/tierlist/traits',
  path: '/tierlist/traits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/champions/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/champions/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/builder': typeof BuilderRoute
  '/champions': typeof ChampionsRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/champions_/$apiName': typeof ChampionsApiNameRoute
  '/comps/$slug': typeof CompsSlugRoute
  '/tierlist/augments': typeof TierlistAugmentsRoute
  '/tierlist/champions': typeof TierlistChampionsRoute
  '/tierlist/comps': typeof TierlistCompsRoute
  '/tierlist/items': typeof TierlistItemsRoute
  '/tierlist/traits': typeof TierlistTraitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/items'
    | '/traits'
    | '/champions/$apiName'
    | '/comps/$slug'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/items'
    | '/traits'
    | '/champions/$apiName'
    | '/comps/$slug'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
  id:
    | '__root__'
    | '/'
    | '/augments'
    | '/builder'
    | '/champions'
    | '/items'
    | '/traits'
    | '/champions_/$apiName'
    | '/comps/$slug'
    | '/tierlist/augments'
    | '/tierlist/champions'
    | '/tierlist/comps'
    | '/tierlist/items'
    | '/tierlist/traits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AugmentsRoute: typeof AugmentsRoute
  BuilderRoute: typeof BuilderRoute
  ChampionsRoute: typeof ChampionsRoute
  ItemsRoute: typeof ItemsRoute
  TraitsRoute: typeof TraitsRoute
  ChampionsApiNameRoute: typeof ChampionsApiNameRoute
  CompsSlugRoute: typeof CompsSlugRoute
  TierlistAugmentsRoute: typeof TierlistAugmentsRoute
  TierlistChampionsRoute: typeof TierlistChampionsRoute
  TierlistCompsRoute: typeof TierlistCompsRoute
  TierlistItemsRoute: typeof TierlistItemsRoute
  TierlistTraitsRoute: typeof TierlistTraitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/augments': {
      id: '/augments'
      path: '/augments'
      fullPath: '/augments'
      preLoaderRoute: typeof AugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traits': {
      id: '/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof TraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions_/$apiName': {
      id: '/champions_/$apiName'
      path: '/champions/$apiName'
      fullPath: '/champions/$apiName'
      preLoaderRoute: typeof ChampionsApiNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comps/$slug': {
      id: '/comps/$slug'
      path: '/comps/$slug'
      fullPath: '/comps/$slug'
      preLoaderRoute: typeof CompsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/augments': {
      id: '/tierlist/augments'
      path: '/tierlist/augments'
      fullPath: '/tierlist/augments'
      preLoaderRoute: typeof TierlistAugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/champions': {
      id: '/tierlist/champions'
      path: '/tierlist/champions'
      fullPath: '/tierlist/champions'
      preLoaderRoute: typeof TierlistChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/comps': {
      id: '/tierlist/comps'
      path: '/tierlist/comps'
      fullPath: '/tierlist/comps'
      preLoaderRoute: typeof TierlistCompsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/items': {
      id: '/tierlist/items'
      path: '/tierlist/items'
      fullPath: '/tierlist/items'
      preLoaderRoute: typeof TierlistItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist/traits': {
      id: '/tierlist/traits'
      path: '/tierlist/traits'
      fullPath: '/tierlist/traits'
      preLoaderRoute: typeof TierlistTraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AugmentsRoute: AugmentsRoute,
  BuilderRoute: BuilderRoute,
  ChampionsRoute: ChampionsRoute,
  ItemsRoute: ItemsRoute,
  TraitsRoute: TraitsRoute,
  ChampionsApiNameRoute: ChampionsApiNameRoute,
  CompsSlugRoute: CompsSlugRoute,
  TierlistAugmentsRoute: TierlistAugmentsRoute,
  TierlistChampionsRoute: TierlistChampionsRoute,
  TierlistCompsRoute: TierlistCompsRoute,
  TierlistItemsRoute: TierlistItemsRoute,
  TierlistTraitsRoute: TierlistTraitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
